markers:
#=================================================#
#                 도로 markers
#                  id: 0 ~ 15
#=================================================#

  - id: 0   # start
    x: 60.0
    y: 18.0
    # yaw: 1.5708   # +90deg (up) 

  - id: 1   # 첫번째 갈림길
    x: 60.0
    y: 54.0
    # yaw: 1.5708   # +90deg (up)

  - id: 2
    x: 18.0
    y: 54.0
    # yaw: -1.5708  # -90deg (down, left column)

  - id: 3
    x: 102.0
    y: 54.0
    # yaw: 1.5708   # +90deg (up, right column)

  - id: 4
    x: 18.0
    y: 111.0
    # yaw: -1.5708

  - id: 5   # 주차구역 1
    x: 42.5
    y: 111.0
    # yaw: 1.5708

  - id: 6   # 주차구역 2
    x: 54.5
    y: 111.0
    # yaw: -1.5708
  
  - id: 7   # 주차구역 3
    x: 66.0
    y: 111.0
    # yaw: 1.5708

  - id: 8   # 주차구역 4
    x: 78.0
    y: 111.0
    # yaw: -1.5708
  
  - id: 9
    x: 102.0
    y: 111.0
    # yaw: 1.5708

  - id: 10
    x: 18.0
    y: 187.0
    # yaw: 1.5708

  - id: 11   # 주차구역 5
    x: 42.5
    y: 187.0
    # yaw: 1.5708

  - id: 12   # 주차구역 6
    x: 54.5
    y: 187.0
    # yaw: 1.5708

  - id: 13   # 주차구역 7
    x: 66.0
    y: 187.0
    # yaw: 1.5708

  - id: 14   # 주차구역 8
    x: 78.0
    y: 187.0
    # yaw: 1.5708

  - id: 15   
    x: 102.0
    y: 187.0
    # yaw: 1.5708

#=================================================#
#                 주차칸 markers
#                  id: 16 ~ 27
#=================================================#

  - id: 16   
    x: 
    y: 

  - id: 17   
    x: 
    y: 

  - id: 18   
    x: 
    y: 

  - id: 19   
    x: 
    y: 

  - id: 20   
    x: 
    y: 

  - id: 21   
    x: 
    y: 

  - id: 22
    x: 
    y: 

  - id: 23   
    x: 
    y: 
  
  - id: 24       
    x: 
    y: 
  
  - id: 25   
    x: 
    y: 
  
  - id: 26
    x: 
    y: 
  
  - id: 27   
    x: 
    y: 
