markers:
#=================================================#
#                 도로 markers
#                  id: 0 ~ 15
#=================================================#

  - id: 0   # start
    x: 60.0
    y: 18.0
    # yaw: 1.5708   # +90deg (up) 

  - id: 1   # 첫번째 갈림길
    x: 60.0
    y: 54.0
    # yaw: 1.5708   # +90deg (up)

  - id: 2
    x: 18.0
    y: 54.0
    # yaw: -1.5708  # -90deg (down, left column)

  - id: 3
    x: 102.0
    y: 54.0
    # yaw: 1.5708   # +90deg (up, right column)

  - id: 4
    x: 18.0
    y: 111.0
    # yaw: -1.5708

  - id: 5   # 주차구역 1
    x: 42.5
    y: 111.0
    # yaw: 1.5708

  - id: 6   # 주차구역 2
    x: 54.5
    y: 111.0
    # yaw: -1.5708
  
  - id: 7   # 주차구역 3
    x: 66.0
    y: 111.0
    # yaw: 1.5708

  - id: 8   # 주차구역 4
    x: 78.0
    y: 111.0
    # yaw: -1.5708
  
  - id: 9
    x: 102.0
    y: 111.0
    # yaw: 1.5708

  - id: 10
    x: 18.0
    y: 187.0
    # yaw: 1.5708

  - id: 11   # 주차구역 5
    x: 42.5
    y: 187.0
    # yaw: 1.5708

  - id: 12   # 주차구역 6
    x: 54.5
    y: 187.0
    # yaw: 1.5708

  - id: 13   # 주차구역 7
    x: 66.0
    y: 187.0
    # yaw: 1.5708

  - id: 14   # 주차구역 8
    x: 78.0
    y: 187.0
    # yaw: 1.5708

  - id: 15   
    x: 102.0
    y: 187.0
    # yaw: 1.5708

#=================================================#
#                 주차칸 markers
#                  id: 16 ~ 27
#=================================================#

  # --- [구역 1] ID 1(y=54)과 ID 5(y=111)의 중간지점 (y=82.5) ---
  - id: 16   
    x: 42.5
    y: 82.5

  - id: 17   
    x: 54.5
    y: 82.5

  - id: 18   
    x: 66.0
    y: 82.5

  - id: 19   
    x: 78.0
    y: 82.5

  # --- [구역 2] ID 5(y=111)와 ID 11(y=187) 사이 3등분 첫번째 줄 (y=136.33) ---
  - id: 20   
    x: 42.5
    y: 136.33

  - id: 21   
    x: 54.5
    y: 136.33

  - id: 22
    x: 66.0
    y: 136.33

  - id: 23   
    x: 78.0
    y: 136.33
  
  # --- [구역 2] ID 5(y=111)와 ID 11(y=187) 사이 3등분 두번째 줄 (y=161.66) ---
  - id: 24       
    x: 42.5
    y: 161.66
  
  - id: 25   
    x: 54.5
    y: 161.66
  
  - id: 26
    x: 66.0
    y: 161.66
  
  - id: 27   
    x: 78.0
    y: 161.66
