image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [592.86897,   0.     , 309.87736,
           0.     , 593.97805, 255.31365,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.186700, -0.514581, -0.011511, -0.005197, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [598.64246,   0.     , 305.77836,   0.     ,
           0.     , 604.58881, 251.29536,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
